# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1468d7901d64e4ffcef9251e31343af2e0336752c6672e2c40b15926ccb94459fb11782ecc2d0c1f1b49e43529b859083287dc054f5998abe15bcbdca97c26db

test:
  secret_key_base: 98e942421d3f16bc2654904f895118fd47f9587ee12234eed4cb2dea8057faabc52d3c8547c7e2b09e6413d42dd96721db45388804cb703f349d0494d112e2e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
